######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 11 21:16:28 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += drawimage.cpp


BUILDDIR = build

DESTDIR = ccp



OBJECTS_DIR = $$BUILDDIR/.obj
MOC_DIR = $$BUILDDIR/.moc
RCC_DIR = $$BUILDDIR/.qrc
UI_DIR = $$BUILDDIR/.ui
